### ISSUE TITLE
Error: read ECONNRESET

### ISSUE THREAD

**Issue by ZombiiTheCoder** [titaniumnetwork-dev/Vanadium#17]
why does this happen

**Comment by Null-n-V0id** [comment]
Hi, can you give the following information so I can get a more detailed report on this subject:

- A link to the instance you're using
- A full copy/paste of the error message
- The website in which you are trying to view in the proxy

Having this additional information will make it much easier to diagnose what is happening and fabricate a solution to your problem.

**Comment by Null-n-V0id** [comment]
Hi. Is there an update on this matter? I would like to look into it and need additional info to pursue this matter any further.

February 10, 2022 5:40:45 PM CET Zombiefiedgamingyt ***@***.***> wrote:

why does this happen
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
-- Sent with https://mailfence.com  Secure and private email

**Comment by Cooldude267** [comment]
The site kinda is down

**Comment by Null-n-V0id** [comment]
I will be closing this issue due to the amount of time it has spent inactive.
